In [2]:
from scipy.io import mmread
import numpy as np
import scipy.sparse as sparse

In [3]:
Hx = mmread('55_codes/55_12_3_Hx.mtx')
Hz = mmread('55_codes/55_12_3_Hz.mtx')
logX = mmread("55_codes/55_12_3_logX.mtx")
logZ = mmread("55_codes/55_12_3_logZ.mtx")

In [5]:
print("X parity checks  | Z parity checks")
for row in range(Hx.shape[0]):
    print(f"{Hx.getrow(row).indices} | {Hz.T.getrow(row).indices}")

print("\nlog X   |  log Z ")
for row in range(logX.shape[0]):
    print(f"{logX.getrow(row).indices} | {logZ.getrow(row).indices}")

X parity checks  | Z parity checks
[11  6  3  1  0] | [7 4 2 1 0]
[17 10  5  2  0] | [12  8  5  3  0]
[24 16  9  4  1] | [18 13  9  6  1]
[27 23 14  7  2] | [25 14 13 10  2]
[29 16 15  8  3] | [26 19 15 11  3]
[26 20 19  7  4] | [25 20 16  8  4]
[23 22 21 12  5] | [21 20 19 17  5]
[29 22 13 10  6] | [27 23 22 11  6]
[25 18 13 12  8] | [26 23 18 12  7]
[28 26 18 15  9] | [28 27 24 14  9]
[27 24 19 17 11] | [29 24 17 16 10]
[28 25 21 20 14] | [29 28 22 21 15]

log X   |  log Z 
[5 1 0] | [7 1 0]
[8 1 0] | [10  1  0]
[8 1 0] | [10  1  0]
[3 2 0] | [7 1 0]
[5 1 0] | [10  1  0]
[8 1 0] | [4 2 0]
[5 1 0] | [7 1 0]
[8 2 0] | [10  1  0]


In [6]:
Hx = mmread("55_codes/55_16_4_Hx.mtx")
Hz =mmread("55_codes/55_16_4_Hz.mtx")
logX = mmread("55_codes/55_16_4_logX.mtx")
logZ = mmread("55_codes/55_16_4_logZ.mtx")

In [7]:
print("X parity checks  | Z parity checks")
for row in range(Hx.shape[0]):
    print(f"{Hx.getrow(row).indices} | {Hz.T.getrow(row).indices}")

print("\nlog X   |  log Z ")
for row in range(logX.shape[0]):
    print(f"{logX.getrow(row).indices} | {logZ.getrow(row).indices}")

X parity checks  | Z parity checks
[32 26 22  9  0] | [32 24 16  8  0]
[34 30 17  8  0] | [34 28 23  9  0]
[32 24 18 14  1] | [32 26 20 15  1]
[34 28 21 15  1] | [34 30 19 14  1]
[38 25 16  8  2] | [36 31 17  8  2]
[36 29 23  9  2] | [38 27 22  9  2]
[36 31 19 14  3] | [38 25 18 14  3]
[38 27 20 15  3] | [36 29 21 15  3]
[33 24 16 10  6] | [33 24 18 12  7]
[33 26 20 13  7] | [33 26 22 11  6]
[35 30 19 12  7] | [35 30 17 10  6]
[35 28 23 11  6] | [35 28 21 13  7]
[37 31 17 10  4] | [39 25 16 10  4]
[39 27 22 11  4] | [37 29 23 11  4]
[39 25 18 12  5] | [39 27 20 13  5]
[37 29 21 13  5] | [37 31 19 12  5]

log X   |  log Z 
[13 12  1  0] | [13 12  1  0]
[3 2 1 0] | [3 2 1 0]
[5 4 1 0] | [10  9  1  0]
[11  8  1  0] | [5 4 1 0]
[11  8  1  0] | [13  9  7  0]
[15  8  4  0] | [13 12  1  0]
[13 12  1  0] | [5 4 1 0]
[15  8  4  0] | [13 12  1  0]
[12 10  4  0] | [13 12  1  0]
[11  8  1  0] | [13 12  1  0]
